name: microcloud
base: core24
assumes:
 - snapd2.59
version: "2.1.0"
grade: stable
source-code: https://github.com/canonical/microcloud.git
summary: Fully automated private clouds
description: |-
 Fully automated private clouds.

confinement: strict

apps:
  # Service
  daemon:
    command: commands/daemon.start
    daemon: simple
    plugs:
      - lxd
      - microceph
      - microovn
      - network
      - network-bind

  # Commands
  microcloud:
    command: commands/microcloud
    plugs:
      - network

parts:
  dqlite:
    source: https://github.com/canonical/dqlite
    source-depth: 1
    source-type: git
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
      - --enable-build-raft
    stage-packages:
      - liblz4-1
      - libsqlite3-0
      - libuv1
    build-packages:
      - liblz4-dev
      - libsqlite3-dev
      - libuv1-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*
      #- lib/*/liblz4.so*  # use liblz4.so from the base snap

  microcloud:
    build-attributes: [core22-step-dependencies]
    source: https://github.com/canonical/microcloud
    source-commit: 7c2ea3b08ec4341664df25b50ab84a1f230df504 # Pre 2.1.0
    source-type: git
    after:
      - dqlite
    build-snaps:
      - go
    plugin: nil
    override-pull: |
      snapcraftctl pull
      set -ex

      # Download the dependencies
      cd microcloud
      go get -d -v -tags=agent ./...
    override-build: |
      set -ex

      git config user.email "noreply@lists.canonical.com"
      git config user.name "MicroCloud snap builder"

      # Setup build environment
      export CGO_CFLAGS="-I${SNAPCRAFT_STAGE}/include/ -I${SNAPCRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${SNAPCRAFT_STAGE}/lib/ -L${SNAPCRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Build the binaries
      cd microcloud
      go build -o "${SNAPCRAFT_PART_INSTALL}/bin/microcloud" -tags=agent ./cmd/microcloud
      go build -o "${SNAPCRAFT_PART_INSTALL}/bin/microcloudd" -tags=agent,libsqlite3 ./cmd/microcloudd
    prime:
      - bin/microcloud
      - bin/microcloudd

  wrappers:
    plugin: dump
    source: snapcraft/
